modLoader="javafml"
loaderVersion="[54,)"
license="MIT License"
[[mods]]
modId="rsx"
version="${file.jarVersion}"
displayName="Easy Redstone Extras"
displayURL="https://www.curseforge.com/minecraft/mc-mods/redstone-extras"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Easy Redstone Extras'''
[[dependencies.rsx]]
    modId="forge"
    mandatory=true
    versionRange="[54,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rsx]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.4,1.22)"
    ordering="NONE"
    side="BOTH"
